### ISSUE TITLE
Question to boot behavior

### ISSUE THREAD

**Issue by Baiyah7o** [phush0/razer-laptop-control#4]
As I set the standard_effect it is only valid after user logged in. So the keyboard is black until the logon was successf. Is it possible to run an service with machine settings to have the keyboard configured after boot.

**Comment by phush0** [comment]
If you set it once it will write effect to keyboard controller so it have to persist in boot until load next time. At least on my machine it is working so. Service is configured to run as user, because on some distros you can not access DBUS as root, and DBUS is used for notifications about power change and inactivity. If you skip --user parameter in system ctl command it will fail to load.

**Comment by Baiyah7o** [comment]
It is not persistent on my system. The keyboard stays black until the Gnome login has completed and the service is started. 
The FN key effect to the F1-12 and arrow keys persists after reboot. (They turn light blueish grey and rest of keyboard goes dark when FN key is pressed)

**Comment by phush0** [comment]
Try set brightness for ac and bat like 30 ac and 20 bat. What effect are you using?

**Comment by Baiyah7o** [comment]
for gaming i am toggeling per script between 
/usr/bin/razer-cli write standard_effect reactive 150 0 255 0
and 
/usr/bin/razer-cli write standard_effect static 0 255 0

**Comment by phush0** [comment]
Now I found that there is a bug and standard effects are not set on boot.
